Metrics:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/Documentation:
  Enabled: false

# This autocorrect is really annoying
Lint/UnusedBlockArgument:
  Enabled: false
