# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rspec"
gem "simplecov"
gem "rubocop"
gem "pry-byebug"
gem "awesome_print"
gem "facets", require: false

gem 'mittsu'
